---
development:
  cloud_name: hq2nrnigk
  api_key: '118734329112377'
  api_secret: Sv6OjZHpdtdR9A9WwscZgVISB84
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hq2nrnigk
  api_key: '118734329112377'
  api_secret: Sv6OjZHpdtdR9A9WwscZgVISB84
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hq2nrnigk
  api_key: '118734329112377'
  api_secret: Sv6OjZHpdtdR9A9WwscZgVISB84
  enhance_image_tag: true
  static_image_support: false
